### ISSUE TITLE
Error when "Add an Image Plate for each Camera" option is checked

### ISSUE THREAD

**Issue by verbal007** [SBCV/Blender-Import-NVM-Addon#1]
First.. THANK YOU for sharing this. I'm very interested in getting this working as I find it will be very useful when it comes to cleaning up the photogrammetry results. I am new to coding with Blender, so excuse  any misinterpretations of the data.

When I use the addon in order to import my NVM file, I receive an error. This seems to be occurring due to the code that is triggered by the import option to "Add an Image Plate for each Camera".

If I uncheck all the options except for the "Import Cameras" option, the script completes and has created cameras for each of my images (though the parent null seems to be rotated -90 degrees). From here I can manually create background images and they line up with the geometry I created (via COLMAP + MeshLab).

Selecting + copy & pasting the error here.  Also attaching my NVM file zipped.
(Note: the order of the "Traceback..." and "location:..." lines are swapped from what is displayed. Copy/pasting flips it?)
```
Traceback (most recent call last):
  File "/home/jerbot/.config/blender/2.79/scripts/addons/nvm_import_export/import_nvm_op.py", line 519, in execute
    camera_scale=self.camera_extent)
  File "/home/jerbot/.config/blender/2.79/scripts/addons/nvm_import_export/import_nvm_op.py", line 294, in add_cameras
    op=op)
  File "/home/jerbot/.config/blender/2.79/scripts/addons/nvm_import_export/import_nvm_op.py", line 360, in add_camera_image_plane
    shader_node_diffuse_bsdf.inputs['Color'])
AttributeError: 'NoneType' object has no attribute 'inputs'

location: <unknown location>:-1
```
[inuksuk.nvm.zip](https://github.com/SBCV/Blender-Import-NVM-Addon/files/2011132/inuksuk.nvm.zip)

**Comment by SBCV** [comment]
I' ll have a look this weekend, 
Bests

**Comment by SBCV** [comment]
Thank you for reporting this bug. This bug appeared when the blender render engine was not set to "Cycles". This addon uses Cycles node system to visualize the image planes. Now it automatically switches to cycles, if image planes are added. (So you don't have to manually change this setting) Can you check out the latest commit and let me know if everything works for you?

**Comment by verbal007** [comment]
Ah!  I tried trouble-shooting it myself and probably wouldn't have realized that the mode wasn't correct. Tested by switching to Cycles and the script ran.  Then I downloaded your update, reset my scene (to Blender Internal renderer) and ran your new script and all went well. Script automatically switched to Cycles and everything imported correctly.

I'm using COLMAP to do my photogrammetry processing, and it seems to crop some of the images when it removes distortions...  buuut... most alignments in Blender seem to be good (good enough).  Now I have something to play with. 

Thank you!  Will keep you in the loop.

**Comment by verbal007** [comment]
Not sure if you get notified of updates to closed issues, but just wanted to say that this is going to be very useful for cleaning up of photogrammetry-created models. I have some ideas for improvements, and am going to use it as an opportunity to dig into Blender's implimentation of Python. 

*note: NVM files that were created using anything but the "SIMPLE_RADIAL" for feature extraction will cause cameras to not line up properly. According to COLMAP, this is a limitation of NVM... not your script, but just wanted to note that.

**Comment by SBCV** [comment]
I still get notifications ;)
I am always open for PR's, so feel free to contribute.

I'm aware of this limitation, but you have to understand that other software packages like openMVG or MVE only support the native NVM format defined by VisualSfM. (This is why this repository does not support the individual camera models of Colmap)
