### ISSUE TITLE
Import, save BLEND, open BLEND, color is black

### ISSUE THREAD

**Issue by enzyme69** [SBCV/Blender-Import-NVM-Addon#2]
I tested this many times, basically importing seems to work fine, I am getting the color on 3D view, I can render at this point.

If I save and re-open the BLEND, however, I am getting black on Particle Color.

Is there something that I forgot to do? Maybe can I save Particle Color as Texture, if we can remesh it?

**Comment by SBCV** [comment]
Hi, this sounds really strange (and is not what I would expect). I ll have a look. However, since I ll be on a conference at the end of this week I may take some time.

**Comment by SBCV** [comment]
Thanks for reporting this bug. The reason for this was that blender does not automatically store image textures. Now the script packs the texture automatically into the blend file. Can you check out the latest commit and tell me if everything works for you?

Cheers
